# Generated by Django 5.0.7 on 2024-08-05 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=122)),
                ('occupation', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=122)),
                ('weight', models.BigIntegerField()),
                ('height', models.CharField(max_length=122)),
                ('fitnessGoal', models.CharField(max_length=122)),
            ],
        ),
    ]
