# Generated by Django 5.0.7 on 2024-08-05 23:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_registration_height_alter_registration_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 8, 6, 4, 24, 29, 807339)),
        ),
    ]
